name: Deploy to server
on:
  push:
    branches:
      - main 

jobs:
  deploying-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_SSH_HOST }}
          username: ${{ secrets.INSTANCE_SSH_USERNAME }}
          key: ${{ secrets.INSTANCE_SSH_KEY }}
          
          script: |
            cd /home/ubuntu/wordpress
            sudo systemctl reload nginx
