name: Deploy to server
on:
  push:
    branches:
      - main 

jobs:
  deploying-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.INSTANCE_SSH_HOST }}
          username: ${{ secrets.INSTANCE_SSH_USERNAME }}
          key: ${{ secrets.INSTANCE_SSH_KEY }}
          source: "/var/www/html/wordpress.serveirc.com"  # Specify the path to your WordPress files
          target: "wordpress"  # Web root directory on the server

      - name: Reload Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_SSH_HOST }}
          username: ${{ secrets.INSTANCE_SSH_USERNAME }}
          key: ${{ secrets.INSTANCE_SSH_KEY }}
          script: |
            sudo systemctl reload nginx

